### PR TITLE
Implemented Volume Control Node

### PR DESCRIPTION
**Pull request by Mher-av**

### CODE REVIEW

**Review by JuliusCosmoRomeo — APPROVED** [review]
Tested it and it works like a charm!

**Comment by Mher-av** [comment]
I have inherited the Volume control node from the CustomFeedbackNode. Also, I have added the Unity Game OSC.

**Comment by Mher-av** [comment]
I've added a warning message for the users' old classifiers.

**Comment by JuliusCosmoRomeo** [comment]
@cyberjunk , could you please re-review? From my end this is fine and works as expected. ✅

**Comment by cyberjunk** [comment]
@JuliusCosmoRomeo My change requests above have not yet been implemented (or at least pushed).

**Comment by Mher-av** [comment]
> This is a websocket client which previously read volumes from the CustomFeedback values which are transmitted to websocket clients. You have to extend the websocket protocol to send volumes to websocket clients as well.

I have changed the parent of the VolumeNode, so now the CustomFeedBack Node is the parent for it. And also have made changes in the Classifier. Now the Classifier holds VolumeNode along with CustomFeedback node.

**Review by cyberjunk — APPROVED** [review]

**Pull request merged**
